absolute_urls: false
default_locale: delete

languages:
  supported: [de]

home:
  alias: '/home'

pages:
  theme: gga
  markdown:
    extra: true
  process:
    markdown: true
    twig: false

dateformat:
  default:                           # The default date format Grav expects in the `date: ` field
  short: 'jS M Y'                    # Short date format
  long: 'F jS \a\t g:ia'             # Long date format
publish_dates: true

cache:
  enabled: false
  check:
    method: file
  driver: auto
  prefix: 'g'
  gzip: true

twig:
  cache: true
  debug: false
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true

errors:
  display: false
  log: true

debugger:
  enabled: false
  twig: false
  shutdown:
    close_connection: true
