absolute_urls: false

home:
  alias: '/home'

pages:
  theme: antimatter
  markdown_extra: false
  process:
    markdown: true
    twig: false

cache:
  enabled: false
  check:
    method: file
  driver: auto
  prefix: 'g'
  gzip: true

twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true

errors:
  display: false
  log: true

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true
