email: mail@samuelstein.de
access:
  admin:
    login: 'true'
    super: 'true'
  site:
    login: 'true'
fullname: 'Samuel Stein'
title: 'Site Admin'
language: de
hashed_password: $2y$10$1ebsNfYDAwJw4LGRRGliQu/1yNdcdEjilQ/YKDcUFrgZeUE1FIbW6
state: enabled
